In [3]:
import numpy as np
from matplotlib import pyplot as plt
from keras.models import load_model
from numpy import argmax
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from tensorflow.keras.datasets import mnist

# load and prepare the image
def load_image(filename):
 # load the image
 img = load_img(filename, color_mode = "grayscale", target_size=(28, 28))
 # convert to array
 img = img_to_array(img)
 # reshape into a single sample with 1 channel
 img = img.reshape(1, 28, 28, 1)
 # prepare pixel data
 img = img.astype('float32')
 img = img / 255.0
 return img

In [4]:
encoder = load_model('../3)_EncoderDecoder/Models/encDense450.keras')  #encDense64    #encCNNNew
decoder = load_model('../3)_EncoderDecoder/Models/decDense450.keras')  #decDense64    #decCNNNew

In [5]:
import pickle
classes = {0:[],1:[],2:[],3:[],4:[],5:[],6:[],7:[],8:[],9:[]}
with open('/content/drive/MyDrive/classes_data.pkl', 'rb') as fp:
    classes = pickle.load(fp)
    print("Success")
print(len(classes[0]))
print(len(classes[1]))
print(len(classes[2]))
print(len(classes[3]))
print(len(classes[4]))
print(len(classes[5]))
print(len(classes[6]))
print(len(classes[7]))
print(len(classes[8]))
print(len(classes[9]))

Success
6903
7877
6990
7141
6824
6313
6876
7293
6825
6958


In [6]:
np.random.seed(2816560083)
rand_index0 = np.random.randint(0,6903,(1,10)) # random numpy array of shape (4,5)

rand_index1 = np.random.randint(0,7877,(1,10)) # random numpy array of shape (4,5)

rand_index2 = np.random.randint(0,6990,(1,10)) # random numpy array of shape (4,5)

rand_index3 = np.random.randint(0,7141,(1,10)) # random numpy array of shape (4,5)

rand_index4 = np.random.randint(0,6824,(1,10)) # random numpy array of shape (4,5)

rand_index5 = np.random.randint(0,6313,(1,10)) # random numpy array of shape (4,5)

rand_index6 = np.random.randint(0,6876,(1,10)) # random numpy array of shape (4,5)

rand_index7 = np.random.randint(0,7293,(1,10)) # random numpy array of shape (4,5)

rand_index8 = np.random.randint(0,6825,(1,10)) # random numpy array of shape (4,5)

rand_index9 = np.random.randint(0,6958,(1,10)) # random numpy array of shape (4,5)

rand_index = [rand_index0,rand_index1,rand_index2,rand_index3,rand_index4,rand_index5,rand_index6,rand_index7,rand_index8,rand_index9]
rand_index = np.array(rand_index)

print(rand_index)

[[[1662 5943 1243 6521 4167 3107 6702 4958 6228 1607]]

 [[ 323 5894  899 4032 5385  375  259 3920 5769 3762]]

 [[3613 6958 2024 2088 3425 5058  681 5856 3941 3512]]

 [[5987 2662 3208 2536 2862 2940 2582 1311 1020  633]]

 [[ 858 4040 3054 2669  989 4409 4642 3738 5339 4380]]

 [[2350 5161 5582 5470 3034 6033 5926 5036  210 3359]]

 [[5297 5511    8 6516 3141 2948  960 2883 1125 5711]]

 [[5695 1876 3354 5273 1138 5761 4591 3871  811 3171]]

 [[6272 2468  882   69 4916 1929 4576 3413 1670 5915]]

 [[4362 1324 4357   61 6609 2358 2151 6575  482  161]]]


In [7]:
base_points =[]
for i in range(10):
  for j in range(10):
    index = rand_index[i][0][j]
    #print(classes[i][index])
    base_points.append(classes[i][index])

In [8]:
import keras.backend as K


def euclidean_distance_loss(y_true, y_pred):
    """
    Euclidean distance loss
    https://en.wikipedia.org/wiki/Euclidean_distance
    :param y_true: TensorFlow/Theano tensor
    :param y_pred: TensorFlow/Theano tensor of the same shape as y_true
    :return: float
    """
    return K.sqrt(K.sum(K.square(y_pred - y_true), axis=-1))


def get_distance(image_data):
  output = np.zeros(100)
  lat = encoder.predict(image_data.reshape(-1,28,28),verbose=0)
  for j in range(100):
    output[j] = euclidean_distance_loss(lat, base_points[j])

  min_at_index = np.argmin(output)

  if(min_at_index>=0 and min_at_index<10):
    label = 0
  elif(min_at_index>=10 and min_at_index<20):
    label = 1
  elif(min_at_index>=20 and min_at_index<30):
    label = 2
  elif(min_at_index>=30 and min_at_index<40):
    label = 3
  elif(min_at_index>=40 and min_at_index<50):
    label = 4
  elif(min_at_index>=50 and min_at_index<60):
    label = 5
  elif(min_at_index>=60 and min_at_index<70):
    label = 6
  elif(min_at_index>=70 and min_at_index<80):
    label = 7
  elif(min_at_index>=80 and min_at_index<90):
    label = 8
  elif(min_at_index>=90 and min_at_index<100):
    label = 9

  return output[min_at_index]


In [ ]:
from PIL import Image, ImageFont, ImageDraw
import matplotlib.pyplot as plt
import numpy as np
import os
# Unicode ranges for emojis
'''
unicode_ranges = [
    (0x1F300, 0x1F64F),
    (0x1F680, 0x1F6FF),
    (0x1F910, 0x1F96B),
    (0x1F980, 0x1F9E0)
]
'''
#Unicode_0000FFEF
emoji_unicode = chr(0x00FFEF)
image_size = (28, 28)
image_Faulty = Image.new("RGBA", image_size, (0, 0, 0))
font = ImageFont.truetype("../Assets/GNUUnifont9FullHintInstrUCSUR.ttf", 28, encoding='unic')
draw = ImageDraw.Draw(image_Faulty)
text_width, text_height = draw.textsize(emoji_unicode, font=font)
text_x = (image_size[0] - text_width) // 2
text_y = (image_size[1] - text_height) // 2
draw.text((text_x, text_y), emoji_unicode, (255, 255, 255), font=font)

image_Faulty = np.asarray(image_Faulty)

Unrendered_Unicode =[]

unicode_ranges = [
    (0x000000, 0x00FFFF),
    (0x010000, 0x01FBFF)
]
flag = False
count = 0
character = []
digits = []
for start, end in unicode_ranges:
    for unicode_value in range(start, end + 1):
        # Convert the Unicode value to the emoji character
        emoji_unicode = chr(unicode_value)

        # Create a new image with white background
        image_size = (28, 28)
        image = Image.new("RGBA", image_size, (0, 0, 0))

        # Load the font
        font = ImageFont.truetype("../Assets/GNUUnifont9FullHintInstrUCSUR.ttf", 28, encoding='unic')

        # Get a drawing context on the image
        draw = ImageDraw.Draw(image)

        # Calculate text size and position to center the emoji
        text_width, text_height = draw.textsize(emoji_unicode, font=font)
        text_x = (image_size[0] - text_width) // 2
        text_y = (image_size[1] - text_height) // 2

        # Draw the emoji on the image
        draw.text((text_x, text_y), emoji_unicode, (255, 255, 255), font=font)
        count+=1

        if(np.array_equal(np.asarray(image), image_Faulty)):
          continue

        else:
          filename = f"emoji_{unicode_value:08X}.png"
          image.save(filename, dpi=(300, 300))

          dis = get_distance(load_image(filename))

          if(dis > 21.0):  #Arbitarily set and check out manually // use your own results or set distance values for each
            character.append(unicode_value)
          else:
            digits.append(unicode_value)

          os.remove(filename)
        #print("Cycled : ",filename)




Streaming output truncated to the last 5000 lines.
<ipython-input-11-80b6e646d507>:53: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(emoji_unicode, font=font)
<ipython-input-11-80b6e646d507>:53: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(emoji_unicode, font=font)
<ipython-input-11-80b6e646d507>:53: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(emoji_unicode, font=font)
<ipython-input-11-80b6e646d507>:53: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  text_width, text_height = draw.textsize(emoji_unicode, font=font)
<ipython-input-11-80b6e646d50

In [ ]:
np.save('/content/drive/MyDrive/digits.npy',np.asarray(digits))
np.save('/content/drive/MyDrive/character.npy',np.asarray(character))